Update creat.yml

diff --git a/.github/workflows/creat.yml b/.github/workflows/creat.yml
--- a/.github/workflows/creat.yml
+++ b/.github/workflows/creat.yml
@@ -20,17 +20,12 @@ jobs:
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"  
 
-      - name: Check if ip/ directory exists
+      - name: Delete IP Folder
         run: |
-          if [ -d "ip/" ]; then
-            echo "Deleting existing ip/ directory"
-            rm -rf ip/
-            git rm -r --cached ip/
-            git commit -m "Delete IP folder"
-            git push
-          else
-            echo "ip/ directory not found, skipping deletion"
-          fi
+          rm -rf ip/
+          git rm -r --cached ip/
+          git commit -m "Delete IP folder"
+          git push
         env:
           PAT: ${{ secrets.GITHUBS_TOKEN }}
 
@@ -55,6 +50,29 @@ jobs:
               echo "Skipping file: $filename because content is empty or '404: Not Found'"
             fi
           done < template_files.txt
+
+      - name: Configure Git
+        env:
+          PAT: ${{ secrets.GITHUBS_TOKEN }}
+        run: |
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub Actions"
+          
+      - name: Add files to Git
+        run: |
+          git add ip/*.txt
+          
+      - name: Check Git status
+        run: |
+          git status
+          
+      - name: Commit changes
+        run: |
+          git commit -m "Update IP files" || echo "Nothing to commit"
+          
+      - name: Push changes
+        run: |
+          git push origin HEAD || echo "Push failed"
 
       - name: Replace IP addresses in template files and merge groups
         run: |
@@ -105,3 +123,6 @@ jobs:
       - name: Push changes
         run: |
           git push origin HEAD || echo "Push failed"
+
+
+
